const mongoose = require("mongoose");
const bcrypt = require("bcrypt");

/*
The user object should store the following information:

username: A unique string that identifies the user's account. It is required and stored as a string.
email: A unique string that represents the user's email address. It is required and stored as a string.
password: A string that represents the user's password. It is required and stored as a string. The password is validated to be at least 8 characters long, and it is encrypted using bcrypt before it is saved to the database.
createdAt: A timestamp that represents the date and time when the user object was created. It is automatically generated by Mongoose and stored as a Date object.
updatedAt: A timestamp that represents the date and time when the user object was last updated. It is automatically generated by Mongoose and stored as a Date object.
Sample User Object:

perl
Copy code
{
  "username": "johndoe",
  "email": "johndoe@example.com",
  "password": "secret123",
  "createdAt": "2023-04-12T08:30:00.000Z",
  "updatedAt": "2023-04-12T08:30:00.000Z"
}
*/
const userSchema = new mongoose.Schema(
	//Write your code here.
);

module.exports = mongoose.model("User", userSchema);
